<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-02-28T18:45:00 EET" name="TestSuite" finished-at="2025-02-28T18:45:08 EET" duration-ms="8448">
    <groups>
    </groups>
    <test started-at="2025-02-28T18:45:00 EET" name="Test1" finished-at="2025-02-28T18:45:08 EET" duration-ms="8448">
      <class name="Tests.LoginTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:Tests.LoginTest@1fa268de]" started-at="2025-02-28T18:45:00 EET" name="setUp" finished-at="2025-02-28T18:45:07 EET" duration-ms="6563" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testLoginLogout()[pri:1, instance:Tests.LoginTest@1fa268de]" started-at="2025-02-28T18:45:07 EET" name="testLoginLogout" finished-at="2025-02-28T18:45:08 EET" duration-ms="1654" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoginLogout -->
        <test-method signature="title()[pri:2, instance:Tests.LoginTest@1fa268de]" started-at="2025-02-28T18:45:08 EET" name="title" finished-at="2025-02-28T18:45:08 EET" duration-ms="31" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- title -->
        <test-method signature="Welcome_to_Secure_Area()[pri:3, instance:Tests.LoginTest@1fa268de]" started-at="2025-02-28T18:45:08 EET" name="Welcome_to_Secure_Area" finished-at="2025-02-28T18:45:08 EET" duration-ms="25" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Subheader message is incorrect! expected [Welcome to the Secure Area. When you are done click logout below.] but found [This is where you can log into the secure area. Enter tomsmith for the username and SuperSecretPassword! for the password. If the information is wrong you should see error messages.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Subheader message is incorrect! expected [Welcome to the Secure Area. When you are done click logout below.] but found [This is where you can log into the secure area. Enter tomsmith for the username and SuperSecretPassword! for the password. If the information is wrong you should see error messages.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at Tests.LoginTest.Welcome_to_Secure_Area(LoginTest.java:54)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Welcome_to_Secure_Area -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Tests.LoginTest@1fa268de]" started-at="2025-02-28T18:45:08 EET" name="tearDown" finished-at="2025-02-28T18:45:08 EET" duration-ms="147" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Tests.LoginTest -->
    </test> <!-- Test1 -->
  </suite> <!-- TestSuite -->
</testng-results>
